
vim.keymap.set("n","<leader><leader>","<cmd>Refresh<CR>" )
vim.keymap.set("n","<leader>w", [[<C-w>w]])
vim.keymap.set("n","<leader>t", "<cmd>ToggleTerm true<CR>")
vim.keymap.set("n","<leader>u", "<cmd>UndotreeToggle<CR>")
vim.keymap.set("n","<leader>q", "<cmd>NvimTreeToggle<CR>")
vim.keymap.set("n","<leader>i", "<cmd>Inspect<CR>")
vim.keymap.set("n","<leader>e", "<cmd>Activate<CR>")
vim.keymap.set("n","<leader>r", "<cmd>Run<CR>")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
vim.keymap.set('n', '<leader>l',"<cmd>Lazy<CR>")
vim.keymap.set('n', '<leader>m',"<cmd>Mason<CR>")
vim.keymap.set('n', '<leader>d',vim.diagnostic.open_float)

vim.keymap.set("t","<C-t>", "<cmd>lua require('termtoggle').toggle(true)<CR>")
vim.keymap.set("t","<Esc>", [[<C-\><C-n>]])
